# Generated by Django 6.0.5 on 2026-05-21 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_supabase_rls_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('ROTATION_A', 'Rotación A (lun-mié / mar-jue)'), ('ROTATION_B', 'Rotación B (mar-jue / lun-mié)'), ('SATURDAY_MONDAY_8H', 'Sábado y lunes 8h'), ('FIXED_4DAY', 'Lunes a jueves fijo'), ('FIXED_CUSTOM', 'Personalizado')], max_length=20)),
                ('custom_weekdays', models.JSONField(blank=True, default=list)),
                ('custom_daily_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_profile', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOvertimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.IntegerField()),
                ('iso_week', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('LOCKED', 'Bloqueada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iso_year', '-iso_week'],
            },
        ),
        migrations.CreateModel(
            name='OvertimePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10)),
                ('source_incidence_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_penalties', to='payroll.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='payroll.weeklyovertimeschedule')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOvertimeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('assignment_type', models.CharField(choices=[('TIPO_1', '1º Tiempo (8h)'), ('TIPO_2', '2º Tiempo (4h)'), ('CUSTOM', 'Personalizado')], max_length=10)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compensation_type', models.CharField(choices=[('PAYROLL', 'Nómina'), ('TXT', 'Tiempo por Tiempo')], default='PAYROLL', max_length=10)),
                ('source', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('is_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_assignments', to='payroll.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payroll.weeklyovertimeschedule')),
            ],
            options={
                'ordering': ['fecha', 'empleado_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyovertimeschedule',
            constraint=models.UniqueConstraint(fields=('iso_year', 'iso_week'), name='unique_overtime_schedule_iso_year_week'),
        ),
        migrations.AddConstraint(
            model_name='overtimepenalty',
            constraint=models.UniqueConstraint(fields=('schedule', 'empleado'), name='unique_overtime_penalty_schedule_empleado'),
        ),
        migrations.AddConstraint(
            model_name='dailyovertimeassignment',
            constraint=models.UniqueConstraint(fields=('schedule', 'empleado', 'fecha'), name='unique_overtime_assignment_schedule_emp_fecha'),
        ),
    ]
